In [108]:
import pandas as pd 
import numpy as np 

walkability_df_raw = pd.read_csv('../data/raw/EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv')
walkability_df = walkability_df_raw.copy()
walkability_df.head()

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,CBSA_Name,CBSA_POP,CBSA_EMP,CBSA_WRK,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,AutoOwn0,Pct_AO0,AutoOwn1,Pct_AO1,AutoOwn2p,Pct_AO2p,Workers,R_LowWageWk,R_MedWageWk,R_HiWageWk,R_PCTLOWWAGE,TotEmp,E5_Ret,E5_Off,E5_Ind,E5_Svc,E5_Ent,E8_Ret,E8_off,E8_Ind,E8_Svc,E8_Ent,E8_Ed,E8_Hlth,E8_Pub,E_LowWageWk,E_MedWageWk,E_HiWageWk,E_PctLowWage,D1A,D1B,D1C,D1C5_RET,D1C5_OFF,D1C5_IND,D1C5_SVC,D1C5_ENT,D1C8_RET,D1C8_OFF,D1C8_IND,D1C8_SVC,D1C8_ENT,D1C8_ED,D1C8_HLTH,D1C8_PUB,D1D,D1_FLAG,D2A_JPHH,D2B_E5MIX,D2B_E5MIXA,D2B_E8MIX,D2B_E8MIXA,D2A_EPHHM,D2C_TRPMX1,D2C_TRPMX2,D2C_TRIPEQ,D2R_JOBPOP,D2R_WRKEMP,D2A_WRKEMP,D2C_WREMLX,D3A,D3AAO,D3AMM,D3APO,D3B,D3BAO,D3BMM3,D3BMM4,D3BPO3,D3BPO4,D4A,D4B025,D4B050,D4C,D4D,D4E,D5AR,D5AE,D5BR,D5BE,D5CR,D5CRI,D5CE,D5CEI,D5DR,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,1,4.811300e+11,4.811300e+11,48,113,7825,4,206.0,"Dallas-Fort Worth, TX-OK",19100.0,"Dallas-Fort Worth-Arlington, TX",7189384,3545715,3364458,73.595028,0.0,73.595028,73.595028,1202,460.0,423.0,0.549,69,0.163121,39,0.092199,315,0.744681,412,99,122,191,0.240291,66,20,3,0,19,24,20,3,0,15,24,0,4,0,21,27,18,0.318182,6.250422,16.332625,0.896800,0.271757,0.040764,0.000000,0.258170,0.326109,0.271757,0.040764,0.000000,0.203818,0.326109,0.000000,0.054351,0.0,7.147222,0,0.156028,0.886264,0.763386,0.855442,0.662091,0.348912,0.526296,0.585916,0.287128,0.104101,0.276151,6.242424,5.287423e-03,23.534900,0.000000,10.655277,12.879623,115.981747,0.000000,60.873677,8.696240,34.784958,43.481198,362.10,0.0,0.000000,4.33,37.654717,0.003602,433601,303660,135362,53504,0.000398,0.785893,0.000358,0.841299,0.000525,0.184697,0.000476,0.137707,6,14,15,17,14.000000,3110.360820,297836.0831
1,2,4.811300e+11,4.811300e+11,48,113,7825,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,"Dallas-Fort Worth-Arlington, TX",7189384,3545715,3364458,119.829909,0.0,119.829909,119.214200,710,409.0,409.0,0.466,0,0.000000,168,0.410758,241,0.589242,395,76,107,212,0.192405,25,7,0,3,15,0,7,0,3,13,0,0,2,0,10,4,11,0.400000,3.430799,5.955666,0.209707,0.058718,0.000000,0.025165,0.125824,0.000000,0.058718,0.000000,0.025165,0.109047,0.000000,0.000000,0.016777,0.0,3.640506,0,0.061125,0.835015,0.569986,0.831686,0.554458,0.197047,0.248481,0.271309,0.002033,0.068027,0.119048,15.800000,3.736300e-07,22.893366,0.755137,2.859482,19.278747,80.145600,5.340904,10.681807,10.681807,85.454458,5.340904,718.84,0.0,0.009516,4.33,23.126113,0.006099,386504,272135,236885,90089,0.000355,0.700531,0.000321,0.753958,0.000919,0.323221,0.000801,0.231868,3,10,12,14,10.833333,3519.469110,484945.1466
2,3,4.811300e+11,4.811300e+11,48,113,7825,3,206.0,"Dallas-Fort Worth, TX-OK",19100.0,"Dallas-Fort Worth-Arlington, TX",7189384,3545715,3364458,26.367053,0.0,26.367053,26.367050,737,365.0,329.0,0.811,19,0.057751,143,0.434650,167,0.507599,463,136,189,138,0.293737,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,13.843035,27.951553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,13.843035,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.367879,0.000000,1.000000,0.000000,0.000000e+00,14.210509,6.128365,2.611430,5.470714,24.272717,24.272717,0.000000,24.272717,0.000000,0.000000,398.31,0.0,0.000000,3.00,72.818150,0.004071,404573,288925,230587,82815,0.000371,0.733281,0.000340,0.800475,0.000894,0.314628,0.000736,0.213146,1,1,7,17,8.333333,1697.091802,106705.9281
3,4,4.811300e+11,4.811300e+11,48,113,7824,1,206.0,"Dallas-Fort Worth, TX-OK",19100.0,"Dallas-Fort Worth-Arlington, TX",7189384,3545715,3364458,119.060687,0.0,119.060687,119.060687,904,384.0,384.0,0.638,0,0.000000,43,0.111979,341,0.888021,431,60,69,302,0.139211,253,26,0,25,47,155,26,0,25,3,155,2,42,0,121,87,45,0.478261,3.225246,7.592767,2.124967,0.218376,0.000000,0.209977,0.394757,1.301857,0.218376,0.000000,0.209977,0.025197,1.301857,0.016798,0.352761,0.0,5.350213,0,0.658854,0.775740,0.668186,0.642754,0.553831,0.682830,0.620719,0.677943,0.596351,0.437338,0.739766,1.703557,4.948219e-01,32.178373,2.208594,9.323547,20.646233,141.604424,21.501640,21.501640,32.252460,134.385248,5.375410,386.24,0.0,0.515377,6.67,35.853984,0.007378,423099,298058,168433,79657,0.000388,0.766859,0.000351,0.825778,0.000653,0.229821,0.000708,0.205018,16,10,17,17,15.666667,2922.609204,481828.4303
4,5,4.811300e+11,4.811300e+11,48,113,7824,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,"Dallas-Fort Worth-Arlington, TX",7189384,3545715,3364458,169.927211,0.0,169.927211,148.742920,948,343.0,343.0,0.506,5,0.014577,67,0.195335,271,0.790087,579,91,84,404,0.157168,32,0,2,10,20,0,0,2,10,19,0,0,1,0,6,9,17,0.187500,2.305992,6.373413,0.215136,0.000000,0.013446,0.067230,0.134460,0.000000,0.000000,0.013446,0.067230,0.127737,0.000000,0.000000,0.006723,0.0,2.521128,0,0.093294,0.755975,0.516033,0.688595,0.459064,0.261472,0.247735,0.258986,0.007903,0.065306,0.104746,18.093750,3.769460e-08,22.058651,2.289659,3.176070,16.592921,65.307963,3.766319,0.000000,7.532637,75.326370,7.532637,638.37,0.0,0.248922,6.67,25.121345,0.007036,335700,238166,120826,48682,0.000308,0.608450,0.000281,0.659846,0.000469,0.164863,0.000433,0.125296,4,7,11,14,10.166667,3731.971773,687684.7752

In [109]:
# Print info about each column
print(walkability_df.info())

# Check for missing values
missing_values = walkability_df.isnull().sum()
print("Missing values in each column:")
print(missing_values.sort_values(ascending=False))

# Show all columns when displaying DataFrames/Series
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
walkability_df.head()

# Print all column names (one per line, no truncation)
# Can't see names when doing walkability_df.columns, so print them one by one
print("All column names:")
for col in walkability_df.columns:
    print(col)

<class 'pandas.DataFrame'>
RangeIndex: 220740 entries, 0 to 220739
Columns: 117 entries, OBJECTID to Shape_Area
dtypes: float64(73), int64(42), str(2)
memory usage: 206.9 MB
None
Missing values in each column:
CSA             53031
CSA_Name        53031
CBSA            17095
CBSA_Name       17095
D1C8_OFF          605
HH                275
CountHU           275
D1A               271
D4D                 1
GEOID10             1
D4E                 1
OBJECTID            0
D2R_JOBPOP          0
D2R_WRKEMP          0
D3A                 0
D2A_WRKEMP          0
D2C_WREMLX          0
D2C_TRPMX2          0
D3AAO               0
D3AMM               0
D3APO               0
D2C_TRIPEQ          0
D2B_E8MIXA          0
D2C_TRPMX1          0
D2A_EPHHM           0
D3BAO               0
D2B_E8MIX           0
D2B_E5MIXA          0
D2B_E5MIX           0
D2A_JPHH            0
D1_FLAG             0
D1D                 0
D1C8_PUB            0
D1C8_HLTH           0
D3B                 0
D4A                 0
D3BMM3              0
D5CE                0
Shape_Length        0
NatWalkInd          0
D4A_Ranked          0
D3B_Ranked          0
D2B_Ranked          0
D2A_Ranked          0
D5DEI               0
D5DE                0
D5DRI               0
D5DR                0
D5CEI               0
D5CRI               0
D3BMM4              0
D5CR                0
D5BE                0
D5BR                0
D5AE                0
D5AR                0
D4C                 0
D4B050              0
D4B025              0
D1C8_ENT            0
D3BPO4              0
D3BPO3              0
D1C8_ED             0
D1C5_ENT            0
D1C8_SVC            0
R_PCTLOWWAGE        0
R_MedWageWk         0
R_LowWageWk         0
Workers             0
Pct_AO2p            0
AutoOwn2p           0
Pct_AO1             0
AutoOwn1            0
Pct_AO0             0
AutoOwn0            0
P_WrkAge            0
TotPop              0
Ac_Unpr             0
Ac_Land             0
Ac_Water            0
Ac_Total            0
CBSA_WRK            0
CBSA_EMP            0
CBSA_POP            0
BLKGRPCE            0
TRACTCE             0
COUNTYFP            0
STATEFP             0
GEOID20             0
R_HiWageWk          0
TotEmp              0
D1C8_IND            0
E5_Ret              0
D1C8_RET            0
D1C5_SVC            0
D1C5_IND            0
D1C5_OFF            0
D1C5_RET            0
D1C                 0
D1B                 0
E_PctLowWage        0
E_HiWageWk          0
E_MedWageWk         0
E_LowWageWk         0
E8_Pub              0
E8_Hlth             0
E8_Ed               0
E8_Ent              0
E8_Svc              0
E8_Ind              0
E8_off              0
E8_Ret              0
E5_Ent              0
E5_Svc              0
E5_Ind              0
E5_Off              0
Shape_Area          0
dtype: int64
All column names:
OBJECTID
GEOID10
GEOID20
STATEFP
COUNTYFP
TRACTCE
BLKGRPCE
CSA
CSA_Name
CBSA
CBSA_Name
CBSA_POP
CBSA_EMP
CBSA_WRK
Ac_Total
Ac_Water
Ac_Land
Ac_Unpr
TotPop
CountHU
HH
P_WrkAge
AutoOwn0
Pct_AO0
AutoOwn1
Pct_AO1
AutoOwn2p
Pct_AO2p
Workers
R_LowWageWk
R_MedWageWk
R_HiWageWk
R_PCTLOWWAGE
TotEmp
E5_Ret
E5_Off
E5_Ind
E5_Svc
E5_Ent
E8_Ret
E8_off
E8_Ind
E8_Svc
E8_Ent
E8_Ed
E8_Hlth
E8_Pub
E_LowWageWk
E_MedWageWk
E_HiWageWk
E_PctLowWage
D1A
D1B
D1C
D1C5_RET
D1C5_OFF
D1C5_IND
D1C5_SVC
D1C5_ENT
D1C8_RET
D1C8_OFF
D1C8_IND
D1C8_SVC
D1C8_ENT
D1C8_ED
D1C8_HLTH
D1C8_PUB
D1D
D1_FLAG
D2A_JPHH
D2B_E5MIX
D2B_E5MIXA
D2B_E8MIX
D2B_E8MIXA
D2A_EPHHM
D2C_TRPMX1
D2C_TRPMX2
D2C_TRIPEQ
D2R_JOBPOP
D2R_WRKEMP
D2A_WRKEMP
D2C_WREMLX
D3A
D3AAO
D3AMM
D3APO
D3B
D3BAO
D3BMM3
D3BMM4
D3BPO3
D3BPO4
D4A
D4B025
D4B050
D4C
D4D
D4E
D5AR
D5AE
D5BR
D5BE
D5CR
D5CRI
D5CE
D5CEI
D5DR
D5DRI
D5DE
D5DEI
D2A_Ranked
D2B_Ranked
D3B_Ranked
D4A_Ranked
NatWalkInd
Shape_Length
Shape_Area

## Walkability dataset — columns we're using

> Column definitions and methodology sourced from the [EPA Smart Location Database Technical Documentation v3.0](https://www.epa.gov/system/files/documents/2023-10/epa_sld_3.0_technicaldocumentationuserguide_may2021_0.pdf)

| Column | What it is | Why we use it |
|---|---|---|
| `GEOID10` | 12-digit Census block group ID | Merge key — links walkability scores to the TIGER shapefile geometries |
| `CBSA` | Metro area code | Filter the national dataset down to San Diego only (code `41740`) |
| `CBSA_Name` | Metro area name | Sanity check that our filter worked correctly |
| `TotPop` | Total population per block group | Useful context for understanding how dense/populated each area is |
| `D1A` | Gross residential density (housing units/acre) | Upstream walkability input used by EPA to calculate `NatWalkInd`; can include placeholder values like `-99999` when data is missing |
| `D3B` | Street intersection density (intersections/sq mile) | Upstream walkability input used by EPA to calculate `NatWalkInd`; can include placeholder values like `-99999` when data is missing |
| `D4A` | Distance to nearest transit stop | Upstream walkability input used by EPA to calculate `NatWalkInd`; can include placeholder values like `-99999` when data is missing |
| `NatWalkInd` | National Walkability Index score (1–20) | EPA's precomputed composite score based on the D-variables, so we can keep just this score instead of carrying the raw D inputs in our beginner workflow |

> The D-variable columns above and all other raw SLD columns are dropped because `NatWalkInd` already incorporates them as a precomputed composite, making the ~110 individual inputs redundant for our project.

In [110]:
cols_to_keep = [
    'GEOID10',       # block group ID — used to merge with TIGER shapefile
    'CBSA',          # filter to San Diego (code 41740)
    'CBSA_Name',     # sanity check that filter worked
    'TotPop',        # total population — useful context
    'NatWalkInd',    # national walkability index — our main scoring input (precomputed by EPA)
]

walkability_df = walkability_df_raw[cols_to_keep].copy()
walkability_df.head()

        GEOID10     CBSA                        CBSA_Name  TotPop  NatWalkInd
0  4.811300e+11  19100.0  Dallas-Fort Worth-Arlington, TX    1202   14.000000
1  4.811300e+11  19100.0  Dallas-Fort Worth-Arlington, TX     710   10.833333
2  4.811300e+11  19100.0  Dallas-Fort Worth-Arlington, TX     737    8.333333
3  4.811300e+11  19100.0  Dallas-Fort Worth-Arlington, TX     904   15.666667
4  4.811300e+11  19100.0  Dallas-Fort Worth-Arlington, TX     948   10.166667

In [111]:
# check nulls in the columns we kept and min/max to understand the range of values
print("Amount of data that isn't null and data types:")
print(walkability_df.info())

print("Summary statistics for numeric columns:")
print(walkability_df.describe())

print("Missing values in each column:")
print(walkability_df.isnull().sum())

Amount of data that isn't null and data types:
<class 'pandas.DataFrame'>
RangeIndex: 220740 entries, 0 to 220739
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   GEOID10     220739 non-null  float64
 1   CBSA        203645 non-null  float64
 2   CBSA_Name   203645 non-null  str
 3   TotPop      220740 non-null  int64
 4   NatWalkInd  220740 non-null  float64
dtypes: float64(3), int64(1), str(1)
memory usage: 13.3 MB
None
Summary statistics for numeric columns:
            GEOID10           CBSA         TotPop     NatWalkInd
count  2.207390e+05  203645.000000  220740.000000  220740.000000
mean   2.870894e+11   30514.836210    1479.863804       9.541628
std    1.640746e+11   10979.471375     987.862242       4.373952
min    1.001020e+10   10100.000000       0.000000       1.000000
25%    1.312100e+11   19740.000000     889.000000       5.833333
50%    2.901900e+11   32820.000000    1265.000000       9.166667
75%    4.200350e+11   39300.000000    1816.000000      13.166667
max    7.803100e+11   49820.000000   55407.000000      20.000000
Missing values in each column:
GEOID10           1
CBSA          17095
CBSA_Name     17095
TotPop            0
NatWalkInd        0
dtype: int64

In [112]:
# understand GEOID10
# pandas read GEOID10 as numeric-looking values, so the raw display can include a trailing .0 and vary in length
raw_geoid10 = walkability_df['GEOID10'].astype(str)
print("Raw GEOID10 examples with lengths:")
for value in raw_geoid10.head():
    print(f"{value} | length: {len(str(value))}")

print("Unique raw GEOID10 lengths:", sorted(raw_geoid10.str.len().unique()))
for length in [14, 13, 3]:
    print(f"Examples of raw GEOID10 values with length {length}:")
    raw_examples = raw_geoid10[raw_geoid10.str.len() == length].head()
    if raw_examples.empty:
        print("None found")
    else:
        print(raw_examples.to_string(index=False))

# convert GEOID10 to clean text by removing the trailing .0 from numeric-looking values so the Census IDs can be compared consistently
def format_geoid10(value):
    if pd.isna(value):
        return value
    try:
        numeric_value = float(value)
        if numeric_value.is_integer():
            return str(int(numeric_value))
    except (TypeError, ValueError):
        pass
    return str(value)

geoid10_text = walkability_df['GEOID10'].map(format_geoid10)
print("Clean GEOID10 examples with lengths:")
for value in geoid10_text.head():
    print(f"{value} | length: {len(str(value))}")

# See if each cleaned GEOID10 has the same length (should be 12 for block groups)
geoid_lengths = geoid10_text.str.len()
unique_lengths = sorted(geoid_lengths.dropna().astype(int).unique())
print("Unique lengths of GEOID10 values:", unique_lengths)

# See examples of cleaned GEOID10 values for each length
for length in unique_lengths:
    print(f"Examples of GEOID10 values with length {length}:")
    print(geoid10_text[geoid_lengths == length].head().to_string(index=False))

Raw GEOID10 examples with lengths:
481130000000.0 | length: 14
481130000000.0 | length: 14
481130000000.0 | length: 14
481130000000.0 | length: 14
481130000000.0 | length: 14
Unique raw GEOID10 lengths: [np.float64(13.0), np.float64(14.0), np.float64(nan)]
Examples of raw GEOID10 values with length 14:
481130000000.0
481130000000.0
481130000000.0
481130000000.0
481130000000.0
Examples of raw GEOID10 values with length 13:
10730059033.0
10730059031.0
10730059053.0
10730059051.0
10730057023.0
Examples of raw GEOID10 values with length 3:
None found
Clean GEOID10 examples with lengths:
481130000000 | length: 12
481130000000 | length: 12
481130000000 | length: 12
481130000000 | length: 12
481130000000 | length: 12
Unique lengths of GEOID10 values: [np.int64(11), np.int64(12)]
Examples of GEOID10 values with length 11:
10730059033
10730059031
10730059053
10730059051
10730057023
Examples of GEOID10 values with length 12:
481130000000
481130000000
481130000000
481130000000
481130000000

In [113]:
# Some GEOID10 values lose their leading zeros when read as numbers so they are length of 11 rather than 12, but they still represent the same block groups. We can confirm this by checking that the shorter values are all missing a leading zero and that adding a leading zero makes them match the longer values.

# Fill in the shorter GEOID10 values with a leading zero due to how pandas read them as numbers
geoid10_text = geoid10_text.apply(lambda x: '0' + x if pd.notna(x) and len(str(x)) == 11 else x)
print("GEOID10 examples after filling leading zeros:")
print(geoid10_text.head())
# Add the cleaned GEOID10 back to the DataFrame and drop the original raw GEOID10 column
walkability_df['GEOID10_clean'] = geoid10_text
walkability_df = walkability_df.drop(columns=['GEOID10'])
walkability_df.head()

GEOID10 examples after filling leading zeros:
0    481130000000
1    481130000000
2    481130000000
3    481130000000
4    481130000000
Name: GEOID10, dtype: str

      CBSA                        CBSA_Name  TotPop  NatWalkInd GEOID10_clean
0  19100.0  Dallas-Fort Worth-Arlington, TX    1202   14.000000  481130000000
1  19100.0  Dallas-Fort Worth-Arlington, TX     710   10.833333  481130000000
2  19100.0  Dallas-Fort Worth-Arlington, TX     737    8.333333  481130000000
3  19100.0  Dallas-Fort Worth-Arlington, TX     904   15.666667  481130000000
4  19100.0  Dallas-Fort Worth-Arlington, TX     948   10.166667  481130000000

In [114]:
# Filter to only San Diego block groups using the cleaned GEOID10 values as we have nulls in the CBSA column
# Also GEOID10 is more reliable than CBSA for filtering to San Diego block groups since some of the CBSA values are null and we know that all San Diego block groups will have GEOID10 values that start with '060730'
# We also will have to merge with the TIGER shapefile using the cleaned GEOID10 values, so it's good to have this column ready for filtering and merging

walkability_df = walkability_df[walkability_df['GEOID10_clean'].str.startswith('060730')] # San Diego block groups start with '060730'
print(walkability_df.head())
print(f"We have {len(walkability_df)} block groups in San Diego after filtering by GEOID10.")

# Find unique CBSA Names
print("Unique CBSA Names in the filtered DataFrame:")
print(walkability_df['CBSA_Name'].unique())

          CBSA                           CBSA_Name  TotPop  NatWalkInd  \
31564  41740.0  San Diego-Chula Vista-Carlsbad, CA    2420    6.666667
31565  41740.0  San Diego-Chula Vista-Carlsbad, CA    1229   10.833333
31566  41740.0  San Diego-Chula Vista-Carlsbad, CA    1627   12.166667
31567  41740.0  San Diego-Chula Vista-Carlsbad, CA    1606    8.166667
31614  41740.0  San Diego-Chula Vista-Carlsbad, CA     592   15.000000

      GEOID10_clean
31564  060730170341
31565  060730170142
31566  060730171042
31567  060730185042
31614  060730075012
We have 1794 block groups in San Diego after filtering by GEOID10.
Unique CBSA Names in the filtered DataFrame:
<ArrowStringArray>
['San Diego-Chula Vista-Carlsbad, CA']
Length: 1, dtype: str

In [115]:
# Check Nulls and Ranges in the San Diego Block Groups Walkability DF
print("Amount of data that isn't null and data types:")
print(walkability_df.info())

Amount of data that isn't null and data types:
<class 'pandas.DataFrame'>
Index: 1794 entries, 31564 to 54638
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CBSA           1794 non-null   float64
 1   CBSA_Name      1794 non-null   str
 2   TotPop         1794 non-null   int64
 3   NatWalkInd     1794 non-null   float64
 4   GEOID10_clean  1794 non-null   str
dtypes: float64(2), int64(1), str(2)
memory usage: 165.1 KB
None

In [116]:
# Check for duplicates in GEOID10
duplicate_geoids = walkability_df['GEOID10_clean'].duplicated().sum()
print(f"Number of duplicate GEOID10 values: {duplicate_geoids}")

Number of duplicate GEOID10 values: 0

## Merging cleaned walkability df 
We will merge the cleaned walkability DataFrame with the TIGER shapefile using `GEOID10_clean` as the shared key. This will attach polygon boundary geometries to each block group, giving each neighborhood a geographic shape that we can use to spatially join crime incidents and assign walkability scores to street edges in our routing algorithm.

In [117]:
# load in the TIGER shapefile for San Diego block groups and check the GEOID10 values there to confirm they match the cleaned GEOID10 values in our walkability DataFrame
import geopandas as gpd
tiger_gdf = gpd.read_file('../data/raw/tl_2020_06_bg/tl_2020_06_bg.shp')
print("TIGER shapefile GEOID10 examples:")
print(display(tiger_gdf.head()))

TIGER shapefile GEOID10 examples:

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,06,053,001500,1,060530015001,Block Group 1,G5030,S,3348560,0,+36.6564570,-121.6749086,"POLYGON ((-121.69184 36.65885, -121.6851 36.66..."
1,06,073,002712,2,060730027122,Block Group 2,G5030,S,337744,0,+32.7303521,-117.0787620,"POLYGON ((-117.08306 32.72588, -117.0828 32.72..."
2,06,073,018601,2,060730186012,Block Group 2,G5030,S,886725,0,+33.2295683,-117.3482855,"POLYGON ((-117.35296 33.22489, -117.35294 33.2..."
3,06,073,018609,3,060730186093,Block Group 3,G5030,S,379311,0,+33.2495250,-117.3148675,"POLYGON ((-117.31819 33.25084, -117.31819 33.2..."
4,06,073,019406,3,060730194063,Block Group 3,G5030,S,649440,0,+33.2018708,-117.2686502,"POLYGON ((-117.2737 33.19762, -117.27367 33.19..."

None

In [118]:
# check datatypes 
print("TIGER shapefile datatypes:")
print(tiger_gdf.dtypes)

# check for missing values 
print("Missing values in each TIGER shapefile column:")
print(tiger_gdf.isnull().sum().sort_values(ascending=False))
# check length of our GEOID values in tiger shapefile
tiger_gdf['GEOID10_length'] = tiger_gdf['GEOID'].astype(str).str.len() # column of length of each rows GEOID value

# unique lengths to see if they are the lengths the block groups are suppose to be
print("Unique lengths of GEOID10 values in TIGER shapefile:", sorted(tiger_gdf['GEOID10_length'].unique()))
print("Examples of GEOID10 values in TIGER shapefile with length 12:")
print(tiger_gdf[tiger_gdf['GEOID10_length'] == 12]['GEOID'].head())

TIGER shapefile datatypes:
STATEFP          str
COUNTYFP         str
TRACTCE          str
BLKGRPCE         str
GEOID            str
NAMELSAD         str
MTFCC            str
FUNCSTAT         str
ALAND          int64
AWATER         int64
INTPTLAT         str
INTPTLON         str
geometry    geometry
dtype: object
Missing values in each TIGER shapefile column:
STATEFP     0
COUNTYFP    0
TRACTCE     0
BLKGRPCE    0
GEOID       0
NAMELSAD    0
MTFCC       0
FUNCSTAT    0
ALAND       0
AWATER      0
INTPTLAT    0
INTPTLON    0
geometry    0
dtype: int64
Unique lengths of GEOID10 values in TIGER shapefile: [np.int64(12)]
Examples of GEOID10 values in TIGER shapefile with length 12:
0    060530015001
1    060730027122
2    060730186012
3    060730186093
4    060730194063
Name: GEOID, dtype: str

In [119]:
print(tiger_gdf.columns)

# keep important columns

tiger_gdf = tiger_gdf[['GEOID', 'geometry']]
print(display(tiger_gdf.head()))

Index(['STATEFP', 'COUNTYFP', 'TRACTCE', 'BLKGRPCE', 'GEOID', 'NAMELSAD',
       'MTFCC', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON',
       'geometry', 'GEOID10_length'],
      dtype='str')

          GEOID                                           geometry
0  060530015001  POLYGON ((-121.69184 36.65885, -121.6851 36.66...
1  060730027122  POLYGON ((-117.08306 32.72588, -117.0828 32.72...
2  060730186012  POLYGON ((-117.35296 33.22489, -117.35294 33.2...
3  060730186093  POLYGON ((-117.31819 33.25084, -117.31819 33.2...
4  060730194063  POLYGON ((-117.2737 33.19762, -117.27367 33.19...

None

In [120]:
"""
Merge the walkability DataFrame with the Tiger shapefile GeoDataFrame on the 
cleaned GEOID10 values to create a GeoDataFrame that includes both the 
walkability data and the geometries for the block groups
"""

walkability_final_gdf = tiger_gdf.merge(walkability_df, left_on="GEOID", right_on="GEOID10_clean", how = "inner")
walkability_final_gdf = walkability_final_gdf.drop(columns=['GEOID10_clean'])
walkability_final_gdf.head()

,GEOID,geometry,CBSA,CBSA_Name,TotPop,NatWalkInd
0,060730027122,"POLYGON ((-117.08306 32.72588, -117.0828 32.72...",41740.0,"San Diego-Chula Vista-Carlsbad, CA",1653,13.500000
1,060730186012,"POLYGON ((-117.35296 33.22489, -117.35294 33.2...",41740.0,"San Diego-Chula Vista-Carlsbad, CA",3958,5.333333
2,060730186093,"POLYGON ((-117.31819 33.25084, -117.31819 33.2...",41740.0,"San Diego-Chula Vista-Carlsbad, CA",2376,13.000000
3,060730194063,"POLYGON ((-117.2737 33.19762, -117.27367 33.19...",41740.0,"San Diego-Chula Vista-Carlsbad, CA",1485,6.500000
4,060730195032,"POLYGON ((-117.24344 33.20156, -117.24329 33.2...",41740.0,"San Diego-Chula Vista-Carlsbad, CA",1079,16.333333